name: todo-app
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    restart: always
  nginx:
    image: nginx:latest
    container_name: todo-app-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend 
  frontend:
    ports:
      - "3000:3000"
    image: node:22
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend:/home/node/app
    expose:
      - "3000"
    command: npm start
    depends_on:
      - backend
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-app-backend
    ports:
      - "8001:3001"
    image: todo-app/backend
    volumes:
      - ./backend:/usr/src/app
    expose:
      - "3001"
    command: python src/server.py
    environment:
      - DEBUG=true
    env_file:
      - path: ./.env
        required: true
    depends_on:
      - mongodb
volumes:
  mongodb_data:

